# DiscordBotに関する設定
Token: [BOTのトークン]
ChannelId: [チェンネルID]
PlayGame: [BOTがプレイ中のゲーム]

# 管理コマンドを実行できるユーザー(ID)
Admin:
- [ユーザーID]

# Minecraftサーバーに関する設定
ServerName: [サーバーの名前]

# Discord コマンドに関する設定
FirstChar: [BOTコマンドの最初の文字]

# 省電力自動クローズ機能
time: [全プレイヤー退出の何分後に閉じるか]

# 各サーバーの設定
Server_List:
- Server1
Server_Info:
  Server1:
    Dir: [サーバー1のディレクトリ]
    File: [サーバー1の実行ファイル名]
    Args: [引数 (-jarは不要)]
    Use_Remote_Console: true #discordコンソール機能を使用するか
    Console_ChannelId: [コンソールチャンネルID(Remote_Consoleがtrueの場合有効)]
