# DiscordBotに関する設定
# Discord bot settings
Token: [BOTのトークン(Bot token)]
ChannelId: [チェンネルID(Channel ID)]
PlayingGame: [BOTがプレイ中のゲーム(The game the bot is playing)]

# 管理コマンドを実行できるユーザーID(Discord)
# User ID that can execute management commands(Discord)
Admin:
- [ユーザーID(User ID)]

# Minecraftサーバーに関する設定
# Minecraft server settings
ServerName: [サーバーの名前(Server name)]

# Discord コマンドに関する設定
# Discord commands settings
FirstString: [BOTコマンドの最初の文字列(First string of BOT commands)]

# Minecraft Discord 相互送信形式
# Minecraft Discord Mutual transmission format
ToDiscord: 【{0}】 {1} ： {2}
ToMinecraft: §1[Discord] §f<{0}> {1}

# 省電力自動サーバー停止機能
# Power saving automatic server stop function
CloseTime: [全プレイヤー退出の何分後に閉じるか(How many minutes after all players leave to close)]

# ------------Added from v5.0-----------
# 起動に必要なリクエスト数
# 0 = 完全に無効, 1 = 一回のリクエストで（すぐに）起動
NumberOf_RequestsRequired: 3
# リクエスト持続時間（分）[最後のリクエストから]
RequestWaitTime: 10
# 再リクエストできる時間
RequestDelay: 3
#---------------------------------------

# 各サーバーの設定 (Server Settings)
# [形式(Format)]
# ServerList:
# - {ID}
# Server:
#   {ID}:
#     Name: ...
# {ID}は Bungeecordのconfig.ymlと同じでなければいけません
# ({ID} must be the same as the setting in Bungeecord config.yml)
Server_List:
- Server1
Server:
  Server1:
    Name: [サーバーの名前(ServerName)]
    Dir: [サーバー1のディレクトリ(Server root directory)]
    File: [サーバー1の実行ファイル名(Server jar file name)]
    Args: [引数(-jarは不要) (Arguments [Don't include -jar argument])]
    Use_Remote_Console: true #discordコンソール機能を使用するか(Whether to use the discord console function)
    Console_ChannelId: [コンソールチャンネルID(Remote_Consoleがtrueの場合有効) (Console channel ID[It is allow when "Use_Remote_Console" is true])]
    advanced:
      LogDeleteRegex: \[[0-9]+:[0-9]+:[0-9]+ .+\]:\s+
      LogServerStartingDone: Done \(\d+\.\d+s\)!.*
      LogServerStopped: Saving worlds
      LogListCmd: There are.+of a max.+players online:.+